Update to `system_builder`
mosdef-hub/reproducibility_study pull request #66
Opened 2021-08-19 23:26 UTC by daico007

This PR will:
1. Add support for `BenzeneUA` and `EthanolAA` 
2. Add way to scale up box size (based on suggestion by @jennyfothergill)

I will try to have this all done and ready for review by this Friday.

2021-08-20 18:04 UTC, jennyfothergill commented
@daico007 I added the scaling in #60, so I could start running sims. Although I think your method of providing scaling factors for each box individually is better. :)

2021-08-23 16:32 UTC, justinGilmer requested changes
Small changes then LGTM!

2021-08-23 16:32 UTC, justinGilmer commented on reproducibility_project/src/molecules/system_builder.py
> +        Option to scaple sizes of the vapor box.
```suggestion
        Option to scale sizes of the vapor box.
```

2021-08-23 16:32 UTC, justinGilmer commented on reproducibility_project/tests/base_test.py
> +    def benzene_uaff(self):
```suggestion
    def benzene_ua_ff(self):
```

2021-08-23 16:32 UTC, justinGilmer commented on reproducibility_project/tests/test_benzene_ua.py
> +    def test_paramters(self, benzene_uaff):
```suggestion
    def test_parameters(self, benzene_ua_ff):
```

2021-08-23 16:32 UTC, justinGilmer commented on reproducibility_project/tests/test_benzene_ua.py
> +        )
```suggestion
        param_struct = benzene_ua_ff.apply(BenzeneUA)

        nonbonded = benzene_ua_ff.get_parameters("atoms", key="CH_sp2")
        bond = benzene_ua_ff.get_parameters(
            "harmonic_bonds", key=["CH_E"] * 2, keys_are_atom_classes=True
        )
        angle = benzene_ua_ff.get_parameters(
            "harmonic_angles", key=["CH_E"] * 3, keys_are_atom_classes=True
        )
        rbtorsion = benzene_ua_ff.get_parameters(
            "rb_propers", key=["CH_E"] * 4, keys_are_atom_classes=True
        )
```

2021-08-23 16:32 UTC, justinGilmer commented on reproducibility_project/tests/test_ethanol_aa.py
> +    """Test to ensure BenzeneUA behaves as expected."""
```suggestion
    """Test to ensure EthanolAA behaves as expected."""
```

2021-08-23 16:56 UTC, jennyfothergill approved these changes
minor change, but otherwise LGTM!

2021-08-23 16:56 UTC, jennyfothergill commented on reproducibility_project/src/molecules/pentane_ua.py
> +    """Create a single particle pentane compound."""
```suggestion
    """Create a united-atom pentane compound."""
```

2021-08-23 19:19 UTC, justinGilmer approved these changes
LGTM!

2021-08-23 19:19 UTC, merged